openapi: 3.0.3
info:
  title: Game Event Tracking – Ingestion API (Test Mode)
  version: 1.0.0
  description: |
    RESTful API for ingesting gameplay events (login and score) from game clients.
    Security removed for testing POST with JSON.

servers:
  - url: http://localhost:8090
    description: Local development

tags:
  - name: Events
    description: Submit and query events

paths:

  /events/login:
    post:
      tags: [Events]
      summary: Ingest a LoginEvent
      operationId: app.post_login_event
      security: []   # بدون API Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginEvent"
            example:
              eventId: "9f2e1db1-b4f6-4e6e-7c2b-3f0a7c4c1010"
              timestamp: "2025-08-28T15:30:00Z"
              clientId: "ios-v1"
              userId: "player_987"
              platform: "ios"
              locale: "fa-IR"
              ip: "198.51.100.23"
      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ack"

  /events/score:
    post:
      tags: [Events]
      summary: Ingest a ScoreEvent
      operationId: app.post_score_event
      security: []   # بدون API Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScoreEvent"
            example:
              eventId: "b7c4c101-3f0a-4e6e-9f2e-1db1b4f67c2b"
              timestamp: "2025-08-28T15:35:05Z"
              clientId: "web-v2"
              userId: "player_123"
              levelId: "stage-5"
              score: 18450
              durationMs: 74210
      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ack"

components:
  schemas:
    Ack:
      type: object
      properties:
        status:
          type: string
          enum: [accepted]
        eventId:
          type: string
      required: [status]

    EventEnvelope:
      type: object
      properties:
        eventId:
          type: string
          format: uuid
        type:
          type: string
          enum: [login, score]
        timestamp:
          type: string
          format: date-time
        clientId:
          type: string
        userId:
          type: string
        payload:
          oneOf:
            - $ref: "#/components/schemas/LoginEventPayload"
            - $ref: "#/components/schemas/ScoreEventPayload"
      required: [type, timestamp, payload]

    LoginEvent:
      allOf:
        - type: object
          properties:
            eventId:
              type: string
              format: uuid
            timestamp:
              type: string
              format: date-time
            clientId:
              type: string
            userId:
              type: string
          required: [timestamp, clientId, userId]
        - $ref: "#/components/schemas/LoginEventPayload"

    LoginEventPayload:
      type: object
      properties:
        platform:
          type: string
        locale:
          type: string
          example: en-US
        ip:
          type: string
          format: ipv4
      required: [platform]

    ScoreEvent:
      allOf:
        - type: object
          properties:
            eventId:
              type: string
              format: uuid
            timestamp:
              type: string
              format: date-time
            clientId:
              type: string
            userId:
              type: string
          required: [timestamp, clientId, userId]
        - $ref: "#/components/schemas/ScoreEventPayload"

    ScoreEventPayload:
      type: object
      properties:
        levelId:
          type: string
        score:
          type: integer
          minimum: 0
        durationMs:
          type: integer
          minimum: 0
      required: [levelId, score]
